### ISSUE TITLE
Replace pycrypto dependency

### ISSUE THREAD

**Issue by jkemp101** [closeio/flask-common#63]
Pycrypto is no longer supported and should be replaced. [Cryptography](https://cryptography.io/en/latest/) package is probably the best choice

**Comment by tsx** [comment]
I think the only thing to do here is swapping out the [AES encryption helpers](https://github.com/closeio/flask-common/blob/master/flask_common/crypto.py) with these https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/

**Comment by jpmelos** [comment]
Dependency dropped in https://github.com/closeio/flask-common/pull/71.
